version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:${PORT:-8081}"
    environment:
      PORT: ${PORT:-8081}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    # depends_on:
      # No more dependency on `db`
      # - db
      # (But this whole section should be removed, right?)
      # If api has no other dependencies, this `depends_on`
      # section can be completely removed.
