services:
  # The API Gateway is the public entry point
  gateway:
    image: nginx:1.21-alpine
    volumes:
      - ./cmd/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80" # Expose NGINX on port 8080
    depends_on:
      - user-service
      - document-service
      - realtime-service

  # User Service for registration and login
  user-service:
    build:
      context: .
      dockerfile: ./cmd/user-service/Dockerfile
    env_file:
      - .env
    environment:
      PORT: "8080"
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}

  # Document Service for metadata and permissions
  document-service:
    build:
      context: .
      dockerfile: ./cmd/document-service/Dockerfile
    env_file:
      - .env
    environment:
      PORT: "8080"
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    

  # Real-time Service for WebSockets
  realtime-service:
    build:
      context: .
      dockerfile: ./cmd/realtime-service/Dockerfile
    env_file:
      - .env
    environment:
      PORT: "8080"
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      # NEW: URL to the internal document-service for auth checks
      DOCUMENT_SERVICE_URL: "http://document-service:8080"
    depends_on:
      - redis
      - document-service

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: