@baseUrl = http://localhost:8081

### 1. Register a new user
# This endpoint creates a new user in the in-memory store.
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "a-very-strong-password"
}

###

### 2. Login with the user to get a JWT
# This request will log in the user created above.
# The @name directive allows us to reference this request's response later.
# @name loginRequest
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "a-very-strong-password"
}

###

### 3. Access a protected route using the JWT
# This request captures the token from the login response and uses it
# in the Authorization header to access a protected endpoint.
@token = {{loginRequest.response.body.token}}

GET {{baseUrl}}/api/me
Authorization: Bearer {{token}}

###

### 4. Create a new document
@token = {{loginRequest.response.body.token}}

POST {{baseUrl}}/api/documents
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "My New Document"
}

###

### 5. Share a document with another user
@token = {{loginRequest.response.body.token}}

POST {{baseUrl}}/documents/48c3b3bd-35e1-405e-ba75-d7336921bb74/share
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "test1@example.com",
  "role": "editor"
}

###

{ "type": "insert", "pos": 11, "text": " pasan", "version": 1 }