apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgres://user:password@db:5432/collaborative_editor_db?sslmode=disable"
  
  REDIS_URL: "redis://redis:6379/0"
  
  DOCUMENT_SERVICE_URL: "http://document-service:8080"
  
  JWT_SECRET: "sample_jwt_secret_key"