name: CD - Deploy to Amazon EKS

on:
  workflow_run:
    workflows: ["CI - Build and Push to ECR"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name collaborative-editor-cluster

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          
      - name: Update Kubernetes manifests
        run: |
          COMMIT_SHA=${{ github.event.workflow_run.head_sha }}
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          AWS_REGION=${{ secrets.AWS_REGION }}

          echo "Updating image tags to commit SHA: $COMMIT_SHA"

          ECR_BASE_PATH="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

          # --- THIS IS THE KEY CHANGE ---
          # We now target the specific -deployment.yaml files, leaving the -service.yaml files untouched.
          yq -i ".spec.template.spec.containers[0].image = \"$ECR_BASE_PATH/user-service:$COMMIT_SHA\"" k8s/user-service-deployment.yaml
          yq -i ".spec.template.spec.containers[0].image = \"$ECR_BASE_PATH/document-service:$COMMIT_SHA\"" k8s/document-service-deployment.yaml
          yq -i ".spec.template.spec.containers[0].image = \"$ECR_BASE_PATH/realtime-service:$COMMIT_SHA\"" k8s/realtime-service-deployment.yaml
          yq -i ".spec.template.spec.containers[0].image = \"$ECR_BASE_PATH/notification-service:$COMMIT_SHA\"" k8s/notification-service-deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          # The apply command remains the same. It will apply all .yaml files in the directory.
          kubectl apply -f k8s/